---
- name: Deploy Journiv (PostgreSQL)
  hosts: homelab-thinkcentre
  become: yes

  vars:
    domain: vojtechmarek.dev
    app_port: "8003"
    
    project_path: "/srv/journiv"
    app_data_path: "{{ project_path }}/data"
    db_path: "{{ project_path }}/postgres"
    redis_path: "{{ project_path }}/valkey"

  tasks:
    - name: Ensure Journiv directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: "1000"
        group: "1000"
      loop:
        - "{{ project_path }}"
        - "{{ app_data_path }}"
        - "{{ db_path }}"
        - "{{ redis_path }}"

    - name: Copy Journiv Environment File
      ansible.builtin.template:
        src: templates/journiv/journiv.env.j2
        dest: "{{ project_path }}/.env"
        mode: '0644'
      notify: Restart Journiv

    - name: Copy Journiv Docker Compose
      ansible.builtin.template:
        src: templates/journiv/journiv.docker-compose.yml.j2
        dest: "{{ project_path }}/docker-compose.yml"
        mode: '0644'
      notify: Restart Journiv

    - name: Ensure Journiv is running
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present

  handlers:
    - name: Restart Journiv
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
        recreate: always